# Generated by Django 3.2.6 on 2022-04-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20220421_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название функционала')),
                ('enabled', models.BooleanField(default=False, verbose_name='Включена')),
                ('count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во если есть')),
            ],
            options={
                'verbose_name': 'Функционал',
                'verbose_name_plural': 'Функционалы',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='personal.subscription', verbose_name='Подписка'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='functions',
            field=models.ManyToManyField(related_name='functions', to='personal.Functions', verbose_name='Функционал подписки'),
        ),
    ]
