# Generated by Django 3.2.6 on 2022-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20220421_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='functions',
        ),
        migrations.AddField(
            model_name='subscription',
            name='change_link',
            field=models.BooleanField(default=False, verbose_name='Смена ссылки вкл/выкл'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='change_link_count',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Кол-во смен ссылки (0 если не ограничено)'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Скидка на услуги партнеров вкл/выкл'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_count',
            field=models.PositiveIntegerField(blank=True, default=10, verbose_name='Величина скидки %'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lock_password',
            field=models.BooleanField(default=False, verbose_name='Пароль блокировки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='personal_site',
            field=models.BooleanField(default=False, verbose_name='Персональный сайт вкл/выкл'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='present',
            field=models.BooleanField(default=False, verbose_name='Подарок'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='present_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название подарка'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='qr_count',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Кол-во QR кодов'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='support',
            field=models.BooleanField(default=False, verbose_name='Обращение в тех поддержку вкл/выкл'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='support_count',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Кол-во обращений в тех поддержку (0 если не ограничено)'),
        ),
        migrations.DeleteModel(
            name='Functions',
        ),
    ]
