# Generated by Django 3.2.6 on 2022-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20220422_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='free_sub',
            field=models.BooleanField(blank=True, default=False, verbose_name='Бесплатная подписка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='change_link',
            field=models.BooleanField(blank=True, default=False, verbose_name='Смена ссылки вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='change_link_count',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Кол-во смен ссылки в год (0 если не ограничено)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.BooleanField(blank=True, default=False, verbose_name='Скидка на услуги партнеров вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lock_password',
            field=models.BooleanField(blank=True, default=False, verbose_name='Пароль блокировки вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='personal_site',
            field=models.BooleanField(blank=True, default=False, verbose_name='Персональный сайт вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='present',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подарок вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='qr_count',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Кол-во QR кодов '),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='support',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обращение в тех поддержку вкл/выкл'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='support_count',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Кол-во обращений в тех поддержку в год (0 если не ограничено)'),
        ),
    ]
