# Generated by Django 3.2.6 on 2022-04-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_qrcode_userlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='enabled',
            field=models.BooleanField(blank=True, null=True, verbose_name='Активность qr кода'),
        ),
    ]
