# Generated by Django 3.2.6 on 2022-04-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20220427_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlinks',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст кнопки'),
        ),
    ]
