# Generated by Django 3.2.6 on 2022-04-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_userlinks_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='link_count',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество доступных ссылок для QR (0 если не ограничено) '),
        ),
    ]
