# Generated by Django 3.2.6 on 2022-04-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_qrcode_link_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='link_count',
        ),
        migrations.AddField(
            model_name='subscription',
            name='link_count',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество доступных ссылок для QR (0 если не ограничено) '),
        ),
    ]
