# Generated by Django 3.2.6 on 2022-04-27 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_auto_20220427_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
