# Generated by Django 3.2.6 on 2022-04-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_alter_qrcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='link_active',
        ),
    ]
