# Generated by Django 3.2.6 on 2022-04-27 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_remove_qrcode_link_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='link_active',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_active', to='personal.userlinks', verbose_name='Активная ссылка'),
        ),
    ]
