# Generated by Django 3.2.6 on 2022-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_qrcode_link_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlinks',
            name='link_icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка кнопки'),
        ),
    ]
