# Generated by Django 3.2.6 on 2022-05-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0021_auto_20220511_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
    ]
